name: celeb3_unconditional

data_loader:
  num_images: 3
  image_size: 64
  dataset: celeb
  seed: 0
  channels: 3

  batch_size: 10

diffusion:
  sigma: 2
  dh: 1
  num_timesteps: 10
  solve_tolerance: 2e-8

training:
  epochs: 750
  lr: 1e-4
  grad_clip: 1 # False or float

  # changes timestep from 0-1 to 0-timestep_multiplier before feeding into network
  timestep_multiplier: 4

model:
  max_positions: 10000 # applys for fourier embedding only
  in_channels: 3
  out_channels: 3
  ch: 128
  ch_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  attention_resolutions: [16, ]
  dropout: 0.1
  resample_with_conv: False
  embedding_method: linear

sample:
  type: unconditional

misc:
  eps: 1e-3

  # how often to sample SSIM and MSE when using --profile flag (seconds)
  profile_freq: 10